import type { Table } from 'dexie';
import { getSupabase, isSupabaseConfigured } from './supabase';
import {
  db,
  SYNC_TABLES,
  rowIdOf,
  getMeta,
  setMeta,
  type SyncTable,
} from '../data/db';

/**
 * Dexie ⇄ Supabase sync (PRD §5.7).
 *
 * Push the outbox, then pull what changed, reconciling per row by
 * last-write-wins on `updatedAt`. Not CRDTs and not per-field merge: the data is
 * a set of flags and a five-item list, so the only realistic conflict is
 * "favourited on my phone, unfavourited on my laptop" — where the later action
 * is the one the rider meant. Per-*row* granularity is the part that matters;
 * it means two different stations favourited on two devices both survive.
 *
 * Everything here is a no-op when unconfigured, signed out, or offline. Sync
 * failing must never be visible as the app failing.
 */

export type SyncState = 'disabled' | 'signed-out' | 'offline' | 'syncing' | 'idle' | 'error';

export interface SyncStatus {
  state: SyncState;
  /** Epoch ms of the last fully successful sync, or null if none yet. */
  lastSyncedAt: number | null;
  /** Rows still waiting to be pushed. */
  pending: number;
  /** Present only in the `error` state. Already human-readable. */
  error?: string;
}

// ─── Row mapping ─────────────────────────────────────────────────────────────
// Client rows and Postgres rows differ in more than case: the client's primary
// key is named per-table (`stationId`, `key`, `name`) while every remote table
// calls it `id`, so the mapping is explicit rather than a camel/snake helper.

interface TableSpec {
  /** Postgres table name. */
  remote: string;
  toRemote(row: Record<string, unknown>, userId: string): Record<string, unknown>;
  fromRemote(row: Record<string, unknown>): Record<string, unknown>;
}

const SPECS: Record<SyncTable, TableSpec> = {
  savedStations: {
    remote: 'saved_stations',
    toRemote: (r, userId) => ({
      user_id: userId,
      id: r.stationId,
      updated_at: r.updatedAt,
      deleted_at: r.deletedAt ?? null,
    }),
    fromRemote: r => ({
      stationId: String(r.id),
      updatedAt: Number(r.updated_at),
      deletedAt: r.deleted_at == null ? null : Number(r.deleted_at),
    }),
  },
  savedJourneys: {
    remote: 'saved_journeys',
    toRemote: (r, userId) => ({
      user_id: userId,
      id: r.key,
      source_id: r.sourceId ?? null,
      dest_id: r.destId ?? null,
      source_name: r.sourceName ?? null,
      dest_name: r.destName ?? null,
      saved_at: r.savedAt,
      updated_at: r.updatedAt,
      deleted_at: r.deletedAt ?? null,
    }),
    fromRemote: r => ({
      key: String(r.id),
      sourceId: r.source_id ?? undefined,
      destId: r.dest_id ?? undefined,
      sourceName: r.source_name ?? undefined,
      destName: r.dest_name ?? undefined,
      savedAt: Number(r.saved_at),
      updatedAt: Number(r.updated_at),
      deletedAt: r.deleted_at == null ? null : Number(r.deleted_at),
    }),
  },
  recentTrips: {
    remote: 'recent_trips',
    toRemote: (r, userId) => ({
      user_id: userId,
      id: r.key,
      source: r.source ?? null,
      dest: r.dest ?? null,
      saved_at: r.savedAt,
      updated_at: r.updatedAt,
      deleted_at: r.deletedAt ?? null,
    }),
    fromRemote: r => ({
      key: String(r.id),
      source: r.source,
      dest: r.dest,
      savedAt: Number(r.saved_at),
      updatedAt: Number(r.updated_at),
      deletedAt: r.deleted_at == null ? null : Number(r.deleted_at),
    }),
  },
  prefs: {
    remote: 'user_prefs',
    toRemote: (r, userId) => ({
      user_id: userId,
      id: r.name,
      value: r.value,
      updated_at: r.updatedAt,
      deleted_at: r.deletedAt ?? null,
    }),
    fromRemote: r => ({
      name: String(r.id),
      value: String(r.value ?? ''),
      updatedAt: Number(r.updated_at),
      deletedAt: r.deleted_at == null ? null : Number(r.deleted_at),
    }),
  },
};

/** Typed-enough handle for generic row work. */
function tableOf(name: SyncTable) {
  return db[name] as unknown as Table<Record<string, unknown>, string>;
}

// ─── Cursors ─────────────────────────────────────────────────────────────────

const cursorKey = (t: SyncTable) => `lastPullAt:${t}`;

/**
 * How far back a pull reaches beyond the stored cursor.
 *
 * `updatedAt` is generated by whichever *device* made the write, so two devices
 * with a minute of clock skew can produce a row whose timestamp is already
 * behind our cursor by the time we see it — invisible forever with an exact
 * `>` cursor. Re-reading a window is free to get wrong: applying a row is
 * idempotent under last-write-wins.
 */
const CURSOR_OVERLAP_MS = 5 * 60 * 1000;

// ─── Status plumbing ─────────────────────────────────────────────────────────

/**
 * Seeded from configuration rather than starting at `'disabled'`.
 *
 * `'disabled'` renders as "sync is not configured for this build", which on a
 * build that *is* configured is simply false — and it would show for the frame
 * between the session resolving and the first drain reporting. Starting at
 * `'signed-out'` is the accurate statement of what we know before asking.
 */
let status: SyncStatus = {
  state: isSupabaseConfigured ? 'signed-out' : 'disabled',
  lastSyncedAt: null,
  pending: 0,
};
const listeners = new Set<(s: SyncStatus) => void>();

export function getSyncStatus(): SyncStatus {
  return status;
}

export function subscribeSyncStatus(fn: (s: SyncStatus) => void): () => void {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

async function setStatus(patch: Partial<SyncStatus>) {
  const pending = await db.syncOutbox.count().catch(() => status.pending);
  status = { ...status, pending, ...patch };
  for (const fn of listeners) fn(status);
}

// ─── Push ────────────────────────────────────────────────────────────────────

/**
 * Drain the outbox.
 *
 * Rows are read from Dexie *now* rather than from the queue entry, so a row
 * mutated three times since being queued pushes its current state once. The
 * upsert is on `(user_id, id)`, making a redelivered push a no-op — which is the
 * one guarantee an offline queue can't make for itself.
 *
 * Outbox entries are deleted only after the server accepts them. A failed push
 * leaves the queue intact to retry; it never drops a write to make progress.
 */
async function push(userId: string): Promise<void> {
  const client = await getSupabase();
  if (!client) return;

  const entries = await db.syncOutbox.toArray();
  if (entries.length === 0) return;

  const byTable = new Map<SyncTable, string[]>();
  for (const e of entries) {
    const list = byTable.get(e.table);
    if (list) list.push(e.rowId);
    else byTable.set(e.table, [e.rowId]);
  }

  for (const [table, rowIds] of byTable) {
    const spec = SPECS[table];
    const local = await tableOf(table).bulkGet(rowIds);

    const payload: Record<string, unknown>[] = [];
    // A queued row that no longer exists locally (cleared local data mid-flight)
    // has nothing to push; drop its entry rather than retrying it forever.
    const orphaned: string[] = [];
    rowIds.forEach((rowId, i) => {
      const row = local[i];
      if (row) payload.push(spec.toRemote(row, userId));
      else orphaned.push(rowId);
    });

    if (payload.length > 0) {
      const { error } = await client.from(spec.remote).upsert(payload, { onConflict: 'user_id,id' });
      // Leave this table's entries queued and let the caller surface the error.
      // Other tables already pushed stay pushed — partial progress is fine
      // because every push is idempotent.
      if (error) throw new Error(`push ${spec.remote}: ${error.message}`);
    }

    const done = payload.length > 0 ? rowIds : orphaned;
    await db.syncOutbox.bulkDelete(done.map(rowId => [table, rowId] as [SyncTable, string]));
  }
}

// ─── Pull ────────────────────────────────────────────────────────────────────

/**
 * Fetch rows changed since the cursor and reconcile them.
 *
 * Two rules that are easy to get wrong:
 *
 * 1. **A pulled row is written without queueing an outbox entry.** Queueing it
 *    would push it straight back and every sync would ping-pong forever.
 * 2. **Rows with a pending outbox entry are skipped.** Their local version
 *    hasn't reached the server yet (a push that failed this round), so applying
 *    the server's older copy over it would silently discard the rider's change.
 *    It gets retried next drain instead.
 */
async function pull(userId: string): Promise<void> {
  const client = await getSupabase();
  if (!client) return;

  for (const table of SYNC_TABLES) {
    const spec = SPECS[table];
    const stored = await getMeta(cursorKey(table));
    const since = stored ? Math.max(0, Number(stored) - CURSOR_OVERLAP_MS) : 0;

    const { data, error } = await client
      .from(spec.remote)
      .select('*')
      .eq('user_id', userId)
      .gt('updated_at', since)
      .order('updated_at', { ascending: true });

    if (error) throw new Error(`pull ${spec.remote}: ${error.message}`);
    if (!data || data.length === 0) continue;

    const pendingIds = new Set(
      (await db.syncOutbox.where('table').equals(table).toArray()).map(e => e.rowId),
    );

    let maxSeen = Number(stored ?? 0);
    const dexieTable = tableOf(table);

    await db.transaction('rw', dexieTable, async () => {
      for (const remoteRow of data as Record<string, unknown>[]) {
        const row = spec.fromRemote(remoteRow);
        const rowId = rowIdOf(table, row);
        maxSeen = Math.max(maxSeen, Number(row.updatedAt));

        if (pendingIds.has(rowId)) continue;

        const existing = await dexieTable.get(rowId);
        // Strictly newer only: on a tie the two copies are the same write as far
        // as LWW can tell, and writing anyway would churn every `useLiveQuery`
        // subscriber on every sync.
        if (existing && Number(existing.updatedAt) >= Number(row.updatedAt)) continue;

        await dexieTable.put(row);
      }
    });

    await setMeta(cursorKey(table), String(maxSeen));
  }
}

// ─── Tombstone pruning ───────────────────────────────────────────────────────

/** Tombstones older than this are dropped locally. See {@link prune}. */
const TOMBSTONE_TTL_MS = 90 * 24 * 60 * 60 * 1000;

/**
 * Drop long-dead tombstones.
 *
 * They exist to stop a pull resurrecting a deleted row, which only needs to hold
 * until every device has seen the delete. After 90 days a device that still
 * hasn't synced will re-add the row, and that is the correct outcome — it means
 * the row was re-created there, not that we lost a delete.
 *
 * Never prunes a row with a pending push: that tombstone hasn't reached the
 * server, and dropping it would lose the delete entirely.
 */
async function prune(): Promise<void> {
  const cutoff = Date.now() - TOMBSTONE_TTL_MS;
  for (const table of SYNC_TABLES) {
    const dexieTable = tableOf(table);
    const dead = (await dexieTable.toArray()).filter(
      r => r.deletedAt != null && Number(r.deletedAt) < cutoff,
    );
    if (dead.length === 0) continue;
    const pendingIds = new Set(
      (await db.syncOutbox.where('table').equals(table).toArray()).map(e => e.rowId),
    );
    const ids = dead.map(r => rowIdOf(table, r)).filter(id => !pendingIds.has(id));
    if (ids.length > 0) await dexieTable.bulkDelete(ids);
  }
}

// ─── Entry point ─────────────────────────────────────────────────────────────

/**
 * Overlapping calls share one run.
 *
 * Sign-in, reconnect and a mutation can all fire within the same tick, and two
 * concurrent drains would push the same outbox entries twice and race on
 * deleting them. Callers get the in-flight promise instead.
 */
let inFlight: Promise<SyncStatus> | null = null;

export function syncNow(): Promise<SyncStatus> {
  if (inFlight) return inFlight;
  inFlight = run().finally(() => {
    inFlight = null;
  });
  return inFlight;
}

async function run(): Promise<SyncStatus> {
  if (!isSupabaseConfigured) {
    await setStatus({ state: 'disabled', error: undefined });
    return status;
  }

  // Checked before the client is loaded, not after: `getSupabase()` fetches a
  // chunk, and asking for one with no network is a guaranteed failure that would
  // also null the memo and make the next attempt re-fetch.
  //
  // navigator.onLine is only reliable in the negative — false genuinely means no
  // network, true means "an interface exists", which a captive portal also
  // satisfies. So it only skips work that's certain to fail; a true value still
  // goes through the try/catch below.
  if (typeof navigator !== 'undefined' && navigator.onLine === false) {
    await setStatus({ state: 'offline', error: undefined });
    return status;
  }

  const client = await getSupabase();
  if (!client) {
    await setStatus({ state: 'disabled', error: undefined });
    return status;
  }

  const { data: sessionData } = await client.auth.getSession();
  const userId = sessionData.session?.user.id;
  if (!userId) {
    await setStatus({ state: 'signed-out', error: undefined });
    return status;
  }

  await setStatus({ state: 'syncing', error: undefined });
  try {
    await push(userId);
    await pull(userId);
    await prune();
    await setMeta('lastSyncedAt', String(Date.now()));
    await setStatus({ state: 'idle', lastSyncedAt: Date.now(), error: undefined });
  } catch (e) {
    // The outbox still holds everything unpushed, so this is a delay, not a
    // loss. Reported so the YOU screen can say "not synced" honestly rather
    // than showing a stale success.
    await setStatus({ state: 'error', error: e instanceof Error ? e.message : String(e) });
  }
  return status;
}

/**
 * Wire the triggers that make sync happen without anyone asking.
 *
 * Called once from the auth provider. Returns a teardown.
 */
export function startSyncTriggers(): () => void {
  const onOnline = () => { void syncNow(); };
  window.addEventListener('online', onOnline);

  // A drain that failed while the tab was backgrounded should retry when the
  // rider comes back, not sit until the next mutation.
  const onVisible = () => {
    if (document.visibilityState === 'visible') void syncNow();
  };
  document.addEventListener('visibilitychange', onVisible);

  return () => {
    window.removeEventListener('online', onOnline);
    document.removeEventListener('visibilitychange', onVisible);
  };
}

/** Restore last-synced time across reloads so the UI isn't blank on boot. */
export async function hydrateSyncStatus(): Promise<void> {
  const last = await getMeta('lastSyncedAt');
  await setStatus({ lastSyncedAt: last ? Number(last) : null });
}
